import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius';
import { BooksModule } from '@alpin11-coding-challenge/libs/api/feature-book';

import { APP_PIPE } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import * as path from 'path';

const validationProviders = {
  provide: APP_PIPE,
  useValue: new ValidationPipe(),
};


@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql'),
    }),    
    BooksModule,
  ],
  providers: [validationProviders],
})
export class AppModule {}
