import '../styles/global.css';
import { ReactNode } from 'react';
// eslint-disable-next-line @nx/enforce-module-boundaries
import {Toaster} from "../../../libs/shared/src/components/ui/sonner";

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  )
}